server:
     port:
          8088 
spring:
  datasource:
        name: 
              foodsafe
        url:
                  jdbc:mysql://192.168.1.127:3306/common?useUnicode=true&characterEncoding=utf8&useSSL=false
        username:
                  hesion
        password:
                  Hesion2017!@$
        type: 
                  com.alibaba.druid.pool.DruidDataSource
        driver-class-name: 
                            com.mysql.jdbc.Driver
  redis:
        cluster:
            nodes:
                192.168.0.189:7001,192.168.0.190:7003,192.168.0.191:7005
#  kafka:
#    bootstrap-servers:
#                192.168.0.189:9092,192.168.0.190:9092,192.168.0.191:9092
mybatis: 
  mapperLocations: 
                    classpath:mapper/*.xml
  typeAliasesPackage: 
                      com.woniu.product
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false